tft:
  - name: "Test 1"
    namespace: "ft"
    # test cases can be specified individually i.e "1,2,3,6" or as a range i.e. "1-9,15-19"
    test_cases: "1"
    duration: "30"
    # Location of artifacts from run can be specified: default <working-dir>/ft-logs/
    # logs: "/tmp/ft-logs"
    connections:
      - name: "Connection_1"
        # supported types: iperf-tcp, iperf-udp, netperf-tcp-stream, netperf-tcp-rr
        type: "iperf-tcp"
        instances: 1
        server:
          - name: "worker-229"
            persistent: "false"
            sriov: "false"
        client:
          - name: "worker-230"
            sriov: "false"
        plugins:
          - name: measure_cpu
          - name: measure_power
          - name: validate_offload
