IPERF_TCP:
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 1
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 2
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 3
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 4
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 5
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 6
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 7
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 8
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 9
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 10
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 11
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 12
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 13
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 14
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 15
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 16
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 17
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 18
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 19
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 20
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 21
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 22
- Normal:
    threshold: 18
  Reverse:
    threshold: 18
  id: 23
- Normal:
    threshold: 12
  Reverse:
    threshold: 13
  id: 24
- Normal:
    threshold: 18
  Reverse:
    threshold: 10
  id: 25
- Normal:
    threshold: 18
  Reverse:
    threshold: 10
  id: 26
- Normal:
    threshold: 18
  Reverse:
    threshold: 10
  id: 27
- Normal:
    threshold: 18
  Reverse:
    threshold: 10
  id: 28
- Normal:
    threshold: 18
  Reverse:
    threshold: 10
  id: 29
- Normal:
    threshold: 18
  Reverse:
    threshold: 10
  id: 30
IPERF_UDP:
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 1
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 2
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 3
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 4
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 5
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 6
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 7
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 8
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 9
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 10
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 11
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 12
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 13
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 14
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 15
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 16
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 17
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 18
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 19
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 20
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 21
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 22
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 23
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 24
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 25
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 26
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 27
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 28
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 29
- Normal:
    threshold: 5
  Reverse:
    threshold: 5
  id: 30

